### PR TITLE
Translated source comments to English

### PR DESCRIPTION
**Pull request by jraviotta**
English-speaking users may find a new branch useful.

### CODE REVIEW

**Comment by rockets-cn** [comment]
Great! Thanks for the tranlate!

**Comment by shanlter** [comment]
@jraviotta Thanks very much! How do you find this project? Do you have any application on water monitoring?

**Comment by jraviotta** [comment]
@shanlter I have a hobby aquaponic system in my home. I am developing an Arduino + Raspberry pi system to monitor and control the mechanics.  See a video here https://youtu.be/TUn8dqpzYbs.

I found the project through DFRobot while searching for an open source water monitoring project to extend for my needs. Thanks for making Know Flow available. It is exactly what I wanted.

**Comment by rockets-cn** [comment]
@jraviotta thank you for contribute for us.  Would you mind to share your project, so we can put the link to the readme.md

**Comment by jraviotta** [comment]
My fork is https://github.com/jraviotta/KnowFlow_AWM. I will be updating with my sensors and will contribute back in pull requests. Feel free to incorporate whatever is useful and ignore the rest.

**Pull request merged**
